### ISSUE TITLE
Topological ordering issue

### ISSUE THREAD

**Issue by mbooth101** [fedora-java/modularity-utils#9]
I also notice an issue in build ordering when I enable build-deps for example, I ended up with this output:

Notice how the build-deps are out of order (e.g.: jackson-bom should be *before* both jackson-core and jackson-databind)

```
            jackson-bom:
                buildorder: 30
                ref: tycho
                arches: [x86_64, ppc64le, aarch64, s390x]
                rationale: >
                    Build dependency of jackson-core, jackson-databind.
            jackson-core:
                buildorder: 10
                ref: tycho
                arches: [x86_64, ppc64le, aarch64, s390x]
                rationale: >
                    Runtime dependency of jackson-databind, mustache-java.
                    Build dependency of jackson-databind, mustache-java.
            jackson-databind:
                buildorder: 20
                ref: tycho
                arches: [x86_64, ppc64le, aarch64, s390x]
                rationale: >
                    Runtime dependency of mustache-java.
                    Build dependency of mustache-java.
            jackson-parent:
                buildorder: 20
                ref: tycho
                arches: [x86_64, ppc64le, aarch64, s390x]
                rationale: >
                    Runtime dependency of jackson-bom.
                    Build dependency of jackson-annotations, jackson-bom.
            replacer:
                buildorder: 10
                ref: tycho
                arches: [x86_64, ppc64le, aarch64, s390x]
                rationale: >
                    Build dependency of jackson-core, jackson-databind.
```
